import type { Metadata } from "next";
import localFont from "next/font/local";
import { MantineProvider } from '@mantine/core';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/STIXTwoText.ttf",
  variable: "--font-Stix",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider withGlobalClasses>
        {children}
        </MantineProvider>
      </body>
      
    </html>
  );
}
